### ISSUE TITLE
Use tagged things for package.json

### ISSUE THREAD

**Issue by kinglozzer** [feejin/Silverstripe-CleanInstall#24]
Rather than `*` which, for example, results in new SCSS-lint errors every time we work on an old project!

**Comment by stnvh** [comment]
:+1: I agree, prevents any breaking changes from plugin updates when doing an ```npm update``` etc.

**Comment by stnvh** [comment]
However in this case, I just realised scss-lint is installed via ruby globally on our machines. The ideal situation would be to fully scope the dependencies to the project - having linter, sass etc. all installed on a per-project basis to prevent the issue of breaking changes being pulled through, or in this case, new lint rules!
