### ISSUE TITLE
Globbing

### ISSUE THREAD

**Issue by kinglozzer** [feejin/Silverstripe-CleanInstall#33]
We can glob our imports with https://github.com/jsahlen/gulp-css-globbing, meaning:

```scss
// Core layout
@import 'layout/*';

// Reusable components
@import 'components/*';
```

Pro: don’t need to manually add a new file when you create it
Con: can’t control import order, I’m guessing it’s alphabetical. Shouldn’t be an issue (if it is, there’s probably something wrong with your CSS), but still

**Comment by feejin** [comment]
This would save me a lot of time wondering why my changes aren't appearing
when I've forgotten to include a new file. Do it.
