### ISSUE TITLE
SCSS Lint – Trailing Newline

### ISSUE THREAD

**Issue by feejin** [feejin/Silverstripe-CleanInstall#42]
Is this actually required by anything?
It's my most common failure apart from property order and I don't know why it's even a check.

**Comment by kinglozzer** [comment]
[Boring answer](http://stackoverflow.com/questions/729692/why-should-files-end-with-a-newline). tldr version: git. Without a new line, it’ll always show the final line in the diff for every commit - even though nothing in the final line changed

**Comment by stnvh** [comment]
@feejin You could probably get a sublime plugin to auto-add newlines on save. Atom does it already, and never knew why until now!

**Comment by feejin** [comment]
FYI, there's a sublime setting:
"ensure_newline_at_eof_on_save": true
